### ISSUE TITLE
Manga livre

### ISSUE THREAD

**Issue by LFC0-0** [Claudemirovsky/unofficial-tachiyomi-extensions#11]
### Source information and language

pt.mangalivre-v1.4.18

### Steps to reproduce

![Screenshot_20230913-002332](https://github.com/Claudemirovsky/unofficial-tachiyomi-extensions/assets/121242940/90d1ed66-751b-4cde-b651-0041f924b1c9)

### Expected behavior

Deveria abrir normalmente as páginas do manga

### Actual behavior

Não abre

### Tachiyomi version

App version: 0.14.3-6151 (standard, 43e8dcd1f, 94, 2023-06-15T08:44Z) Android version: 10 (SDK 29) Android build ID: QPZS30.30-Q3-38-69-12 Device brand: motorola Device manufacturer: motorola Device name: guam Device model: moto e(7) plus Device product name: guam_retail

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Ok, fixed.
