### ISSUE TITLE
SIRIUS

### ISSUE THREAD

**Issue by LFC0-0** [Claudemirovsky/unofficial-tachiyomi-extensions#9]
### Source name

Sirius scanlator

### Source link

https://siriusscanlator.com/

### Language

PT BR 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Claudemirovsky** [comment]
Ao que vi, essa fonte NÃO possui um leitor próprio integrado, portanto não farei uma extensão.
